include:
 - project: 'ProtonVPN/Linux/_gitlab-ci'
   ref: new_client
   file: 'gitlab-ci-build-publish-pypi.yml'

unit-tests:
  extends: .unit-tests
  before_script:
    - apt update
    - apt install -y libgirepository1.0-dev
    - apt install -y libdbus-1-dev
    - apt install -y gir1.2-nm-1.0

pypi-publish:
  extends: .pypi-publish